### ISSUE TITLE
Using as a library?

### ISSUE THREAD

**Issue by matthiasbeyer** [Exein-io/pulsar#105]
Hi, I cannot find a way to use this crate as a library, is there any?

**Comment by MatteoNardi** [comment]
There are two ways to reuse the agent's modules:
- Depend on the `pulsar` crate, add [your own modules](https://github.com/Exein-io/pulsar/blob/main/bpf-common/ProbeTutorial.md) and build a custom agent.
  You do this by copying the [main](https://github.com/Exein-io/pulsar/blob/main/pulsar/src/main.rs) file and changing the module list. 
- Depend on a single module and use it as a library

I'll assume you're interested about the second one.
Each Pulsar module contain a `program` function, a pulsar integration module and unit tests. 
```rust
pub async fn program(ctx: BpfContext, sender: impl BpfSender<FsEvent>) -> Result<Program, ProgramError>
```
You can call this by passing configuration (`BpfContext`) and a channel where events will be sent (for example we've implemented BpfSender for `tokio::sync::mpsc::Sender`). To shut down the probe, you just have to drop the returned `Program`.

This can be seen in the [probe example](https://github.com/Exein-io/pulsar/blob/main/pulsar/src/bin/probe.rs), which runs a single module without the agent itself.

The only issue we know of is that you'll still depend on `pulsar-core`, even if it's unneeded. We should fix it by adding a `pulsar` feature flag in each module.

We should create an example repository documenting both approaches. In the meantime, you're more than welcome to ask questions if you get stuck. We've designed the module system to make it easy to reuse the probes, we'd be happy to get some feedback on it.

**Comment by matthiasbeyer** [comment]
> Depend on the pulsar crate

The [pulsar crate](https://crates.io/crates/pulsar) seems to be a library for the Apache Pulsar infrastructure though!

> You do this by copying the [main](https://github.com/Exein-io/pulsar/blob/main/pulsar/src/main.rs) file and changing the module list.

So there is no way for me to programmatically pass configuration to pulsar as a whole? Only by re-using modules and using the mentioned `BpfContext`?

---

What I would be interested in would be a way to start pulsar and attach it to another program via some IPC, think JSON over HTTP, gRPC, etc etc.

Also, embedding pulsar into my own application would be of interest. That would mean that I would embed the whole `pulsard`, passing configuration programmatically, getting events via callbacks or channels and handling them in my own code (for example to feed them to another system).

---

Either way, thanks for the fast reply and I am really looking forward to explore my options with pulsar!

**Comment by MatteoNardi** [comment]
> The [pulsar crate](https://crates.io/crates/pulsar) seems to be a library for the Apache Pulsar infrastructure though!

True. Note that we're not publishing on `crates.io` and we're not committing to stable APIs yet. You'll have to depend on a git tag/commit. For example:
```
bpf-common = { git = "https://github.com/Exein-io/pulsar", rev = "ba80c9336bcfc09d982d809c62ed3efa0a072e94" } 
pulsar-core = { git = "https://github.com/Exein-io/pulsar", rev = "ba80c9336bcfc09d982d809c62ed3efa0a072e94" }
pulsar = { git = "https://github.com/Exein-io/pulsar", rev = "ba80c9336bcfc09d982d809c62ed3efa0a072e94" }     
```
> So there is no way for me to programmatically pass configuration to pulsar as a whole? Only by re-using modules and using the mentioned BpfContext?

You can either:
- Reuse single modules (with BpfContext and a channel)
- Add your own module
- Configure and control the running `pulsard` instance with the `pulsar` binary

> Also, embedding pulsar into my own application would be of interest. That would mean that I would embed the whole pulsard, passing configuration programmatically, getting events via callbacks or channels and handling them in my own code (for example to feed them to another system).

Nice. I would advice you to build your own module and build a custom agent than. The [module tutorial](https://github.com/Exein-io/pulsar/blob/main/bpf-common/ProbeTutorial.md) is an eBPF event producer, but [the ModuleContext](https://github.com/Exein-io/pulsar/blob/main/bpf-common/ProbeTutorial.md#pulsar-integration) can be used to read events and configure/control the rest of the system. Let us know if you need help.

BTW, for transparency, this is exactly how we're using Pulsar at Exein. This repo contains the core agent and all the modules of public interest. Then we have an internal repository containing some proprietary modules, like ML-based threat detection or sending events to remote servers of our clients.

**Comment by banditopazzo** [comment]
> Hi, I cannot find a way to use this crate as a library, is there any?

You are right, we don't have examples in the docs. I will try to add few tutorials as soon as possible
