### ISSUE TITLE
Optimize perf events map size

### ISSUE THREAD

**Issue by JuxhinDB** [Exein-io/pulsar#12]
During tests @krsh  found that pulsar was consuming 250-650Mb of RAM.

Reducing the number of max entries for perf event maps of PERF_PAGES from 4096 to 1 from improves the situation, but we start loosing events.

Perf event maps size is configured in user space as number of pages of memory.
That number is multiplied by the number of cores, because a copy is kept on every CPU.
That number is multiplied also by the number of modules, because each module has its own map.
A bigger PERF_PAGES value increases memory usage, but makes us less susceptible to losing messages when many events are fired over a very short period of time.

The current memory usage for these maps is - `n. modules * n. cores * PERF_PAGES * page size = 3 * 8 * 4096 * 4Kb = ~400Mb`

These are some ideas to reduce it:

* Using a eBPF [ringbuffer map](https://nakryiko.com/posts/bpf-ringbuf/) instead of perf event map would reduce memory usage by the number of CPU. It's available in kernel >= 5.8. Aya doesn't support it yet.
* We could use a single pinned map for events, shared by all modules. This would reduce memory usage by the number of modules, but would reduce modularity.
* We could make PERF_PAGES setting configurable on a per-module basis. This would allow users to fine tune to their use case to their need. It would also allow us to have different defaults depending on the module type (for example, fs-monitor sends bursts of events because when a program is started, there's a file opened event for every shared library used)
* Reducing the size of events payload would allow us to reduce PERF_PAGES. A problem we have right now is that we transfer the maximum event size even for smaller events. For example, if we have a network sendmsg of 4 bytes, we send 4Kb (the max size) anyway.

---

Original issue author: @MatteoNardi

**Comment by giovannialberto** [comment]
Closing this for the time being as Pulsar doesn't consume this amount of RAM anymore. We lowered default PERF_PAGES map size. Might reopen in the future for further improvements.
