### ISSUE TITLE
`bpf_loop` not detected

### ISSUE THREAD

**Issue by banditopazzo** [exein-io/pulsar#300]
I'm getting:

```console
[2024-06-19T12:04:36Z WARN  bpf_feature_autodetect::func] Function `bpf_loop` (181) not supported in program type BPF_PROG_TYPE_KPROBE
```

but it should be present.

System details:
OS: Arch
Kernel 6.9.3

**Comment by vadorovsky** [comment]
The most important thing about this PR - it's introducing the first ever Rust probe in Pulsar!!!

[![RUST](https://img.youtube.com/vi/TGfQu0bQTKc/0.jpg)](https://www.youtube.com/watch?v=TGfQu0bQTKc)
