### ISSUE TITLE
Logger module ignores the config

### ISSUE THREAD

**Issue by victorazzam** [exein-io/pulsar#310]
Hi folks!

I've been experiencing issues with getting Pulsar to produce JSON output. I am running Pulsar in a test environment and it correctly logs threat events based on a couple of rules I defined. The trouble is that the only output I am getting is in the console and in the default format. It seems the logger config is being ignored, and I can't find anything in the syslog even with it enabled.

Please excuse my naiveté in case I misunderstood the premise of the logger module entirely. Nonetheless, how do I troubleshoot this dillemma? Thanks in advance!

**Comment by banditopazzo** [comment]
Hi, thank for reaching us. 

The first thing you can do is to run `pulsar-exec pulsar config -m logger` (or `pulsar` instead of `pulsar-exec pulsar` if you have the helper scripts) to check the configuration.

I tried the main branch with the following configuration in the `pulsar.ini` and I am getting the JSON output.

```ini
# ...

[logger]
output_format=json
syslog=true

# ...
```

can you send your logger configuration?

**Comment by victorazzam** [comment]
```
$ pulsar config -m logger
+---------------+-------+
| KEY           | VALUE |
+=======================+
| console       | true  |
|---------------+-------|
| enabled       | true  |
|---------------+-------|
| output_format | json  |
|---------------+-------|
| syslog        | true  |
+---------------+-------+
```

**Comment by victorazzam** [comment]
I later tried running it within Docker (`--privileged --net=host --pid=host --cgroupns=host`) and still no dice. Should I be seeing JSON in the standard output/error using the above config?

**Comment by victorazzam** [comment]
Regarding syslog any ideas why could this be?
<img width="542" alt="screenshot" src="https://github.com/user-attachments/assets/177aa0d9-f036-40f2-8c9d-6d18432d91fc">

**Comment by banditopazzo** [comment]
@victorazzam my mistake, when I tested the logger probably I used a dirty configuration file

**Comment by banditopazzo** [comment]
about the syslog issue if you want to send threat to the host syslog service from the container you have to mount the syslog socket in the container.

In general syslog socket is located at one of the following paths:  

- `/dev/log`
- `/var/run/syslog`
- `/var/run/log`

Example of docker command line:

```shell
docker run ... -v /dev/log:/dev/log ...
```
