### ISSUE TITLE
create pulsar docker image

### ISSUE THREAD

**Issue by giovannialberto** [exein-io/pulsar#36]
Dockerize and distribute Pulsar as a public Docker image for getting started with zero overhead.

**Comment by hnidoaht-101** [comment]
hi, I also have a draft dockerfile/docker-compose setup for this one already. If anyone are looking at it, please ignore. I'd like to push it for review soon.

**Comment by hnidoaht-101** [comment]
hi, is there any specific requirements for this issue except the basic ones? Such as publish it to ghcr / docker hub / quay.io, etc...?

**Comment by banditopazzo** [comment]
we want to publish to docker hub with our company account
