### ISSUE TITLE
build SMTP integration for threats logging

### ISSUE THREAD

**Issue by giovannialberto** [Exein-io/pulsar#40]
Implement a Pulsar module to send out Pulsar threat notifications via email through SMTP.

**Comment by mxdblcf** [comment]
Hello, I have some ideas to complete this SMTP issue. I would like to confirm whether the final mode of use presented to users is terminal command or other methods.

**Comment by banditopazzo** [comment]
hi, sorry for responding late I was on vacation last week.

honestly I didn't understand what you mean.

however the module should be similar to this [example](https://github.com/Exein-io/pulsar/blob/main/examples/pulsar-extension-module/my_custom_module.rs).

basically it should read configuration using the already provided method on `ModuleContext`, instantiate a sort of "smtp client" and then watch for incoming threats from the bus and send them using this object. 

it should do this operation in the usual `loop-tokio::select` way, like the example
