### ISSUE TITLE
implement linux desktop notifications

### ISSUE THREAD

**Issue by giovannialberto** [Exein-io/pulsar#41]
Make it possible to send Pulsar threat alerts as notifications when running on a Linux desktop.

Support for principal desktop environments: gnome, plasma kde, etc.

**Comment by MatteoNardi** [comment]
Linux desktop notifications are sent with dbus messages following the XDG specification. My first attempt was using [notify-rust](https://github.com/hoodie/notify-rust). Unfortunately sending them from an application running as root [is complicated](https://stackoverflow.com/a/6732456/4074995).

I'll try to work-around this limitation by spawning something similar to
```
sudo -u matteo  DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send "Pulsar threat"
```

While this is a sub-optimal solution, I think it's acceptable given the goal is ease of use for first-time users.
